// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArtifactType represents the type of artifact
type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0
	ArtifactType_SOURCE_CODE               ArtifactType = 1 // Source code archive
	ArtifactType_SCAN_RESULTS              ArtifactType = 2 // Raw scanner output (JSON/SARIF)
	ArtifactType_REPORT                    ArtifactType = 3 // Generated PDF/HTML reports
	ArtifactType_LOG                       ArtifactType = 4 // Scan execution logs
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "SOURCE_CODE",
		2: "SCAN_RESULTS",
		3: "REPORT",
		4: "LOG",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"SOURCE_CODE":               1,
		"SCAN_RESULTS":              2,
		"REPORT":                    3,
		"LOG":                       4,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

// Artifact represents a stored file/object
type Artifact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScanId         string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Type           ArtifactType           `protobuf:"varint,4,opt,name=type,proto3,enum=cloudscan.storage.ArtifactType" json:"type,omitempty"`
	Filename       string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType    string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	StoragePath    string                 `protobuf:"bytes,8,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *Artifact) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Artifact) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *Artifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Artifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Artifact) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Artifact) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Artifact) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CreateArtifactRequest - Get presigned upload URL
type CreateArtifactRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScanId         string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Type           ArtifactType           `protobuf:"varint,3,opt,name=type,proto3,enum=cloudscan.storage.ArtifactType" json:"type,omitempty"`
	Filename       string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType    string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ExpiresInHours int32                  `protobuf:"varint,7,opt,name=expires_in_hours,json=expiresInHours,proto3" json:"expires_in_hours,omitempty"` // Default: 24 hours
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateArtifactRequest) Reset() {
	*x = CreateArtifactRequest{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactRequest) ProtoMessage() {}

func (x *CreateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArtifactRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CreateArtifactRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateArtifactRequest) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *CreateArtifactRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateArtifactRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateArtifactRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateArtifactRequest) GetExpiresInHours() int32 {
	if x != nil {
		return x.ExpiresInHours
	}
	return 0
}

// CreateArtifactResponse - Returns presigned upload URL
type CreateArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`                                                                                       // Presigned URL for upload
	UploadHeaders map[string]string      `protobuf:"bytes,3,rep,name=upload_headers,json=uploadHeaders,proto3" json:"upload_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Required headers for upload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactResponse) Reset() {
	*x = CreateArtifactResponse{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactResponse) ProtoMessage() {}

func (x *CreateArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactResponse.ProtoReflect.Descriptor instead.
func (*CreateArtifactResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *CreateArtifactResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateArtifactResponse) GetUploadHeaders() map[string]string {
	if x != nil {
		return x.UploadHeaders
	}
	return nil
}

// GetArtifactRequest - Get presigned download URL
type GetArtifactRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresInHours int32                  `protobuf:"varint,2,opt,name=expires_in_hours,json=expiresInHours,proto3" json:"expires_in_hours,omitempty"` // Default: 1 hour
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtifactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetArtifactRequest) GetExpiresInHours() int32 {
	if x != nil {
		return x.ExpiresInHours
	}
	return 0
}

// GetArtifactResponse - Returns presigned download URL
type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // Presigned URL for download
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// DeleteArtifactRequest
type DeleteArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactRequest) Reset() {
	*x = DeleteArtifactRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactRequest) ProtoMessage() {}

func (x *DeleteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArtifactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListArtifactsRequest
type ListArtifactsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScanId         string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Type           ArtifactType           `protobuf:"varint,3,opt,name=type,proto3,enum=cloudscan.storage.ArtifactType" json:"type,omitempty"`
	PageSize       int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtifactsRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ListArtifactsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListArtifactsRequest) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *ListArtifactsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArtifactsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListArtifactsResponse
type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ListArtifactsResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListArtifactsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// InitiateMultipartRequest
type InitiateMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartRequest) Reset() {
	*x = InitiateMultipartRequest{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartRequest) ProtoMessage() {}

func (x *InitiateMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartRequest.ProtoReflect.Descriptor instead.
func (*InitiateMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *InitiateMultipartRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

// InitiateMultipartResponse
type InitiateMultipartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartResponse) Reset() {
	*x = InitiateMultipartResponse{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartResponse) ProtoMessage() {}

func (x *InitiateMultipartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartResponse.ProtoReflect.Descriptor instead.
func (*InitiateMultipartResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *InitiateMultipartResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// GetMultipartPartsRequest
type GetMultipartPartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FromPart      int32                  `protobuf:"varint,3,opt,name=from_part,json=fromPart,proto3" json:"from_part,omitempty"` // Starting part number (1-based)
	NumParts      int32                  `protobuf:"varint,4,opt,name=num_parts,json=numParts,proto3" json:"num_parts,omitempty"` // Number of parts to get URLs for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipartPartsRequest) Reset() {
	*x = GetMultipartPartsRequest{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipartPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartPartsRequest) ProtoMessage() {}

func (x *GetMultipartPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartPartsRequest.ProtoReflect.Descriptor instead.
func (*GetMultipartPartsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *GetMultipartPartsRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *GetMultipartPartsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *GetMultipartPartsRequest) GetFromPart() int32 {
	if x != nil {
		return x.FromPart
	}
	return 0
}

func (x *GetMultipartPartsRequest) GetNumParts() int32 {
	if x != nil {
		return x.NumParts
	}
	return 0
}

// GetMultipartPartsResponse
type GetMultipartPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*UploadPart          `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipartPartsResponse) Reset() {
	*x = GetMultipartPartsResponse{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipartPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartPartsResponse) ProtoMessage() {}

func (x *GetMultipartPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartPartsResponse.ProtoReflect.Descriptor instead.
func (*GetMultipartPartsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *GetMultipartPartsResponse) GetParts() []*UploadPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// UploadPart represents a presigned URL for a multipart upload part
type UploadPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Expiration    string                 `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPart) Reset() {
	*x = UploadPart{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPart) ProtoMessage() {}

func (x *UploadPart) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPart.ProtoReflect.Descriptor instead.
func (*UploadPart) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *UploadPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPart) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadPart) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

// CompleteMultipartRequest
type CompleteMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts         []*CompletedPart       `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartRequest) Reset() {
	*x = CompleteMultipartRequest{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartRequest) ProtoMessage() {}

func (x *CompleteMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartRequest.ProtoReflect.Descriptor instead.
func (*CompleteMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteMultipartRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *CompleteMultipartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteMultipartRequest) GetParts() []*CompletedPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// CompletedPart represents a completed upload part with its ETag
type CompletedPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedPart) Reset() {
	*x = CompletedPart{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedPart) ProtoMessage() {}

func (x *CompletedPart) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedPart.ProtoReflect.Descriptor instead.
func (*CompletedPart) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *CompletedPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *CompletedPart) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// CompleteMultipartResponse
type CompleteMultipartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Expiration    string                 `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartResponse) Reset() {
	*x = CompleteMultipartResponse{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartResponse) ProtoMessage() {}

func (x *CompleteMultipartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartResponse.ProtoReflect.Descriptor instead.
func (*CompleteMultipartResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteMultipartResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CompleteMultipartResponse) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

// AbortMultipartRequest
type AbortMultipartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartRequest) Reset() {
	*x = AbortMultipartRequest{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartRequest) ProtoMessage() {}

func (x *AbortMultipartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartRequest.ProtoReflect.Descriptor instead.
func (*AbortMultipartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *AbortMultipartRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AbortMultipartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x11cloudscan.storage\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x03\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.cloudscan.storage.ArtifactTypeR\x04type\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12!\n" +
	"\fstorage_path\x18\b \x01(\tR\vstoragePath\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x96\x02\n" +
	"\x15CreateArtifactRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.cloudscan.storage.ArtifactTypeR\x04type\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12(\n" +
	"\x10expires_in_hours\x18\a \x01(\x05R\x0eexpiresInHours\"\x97\x02\n" +
	"\x16CreateArtifactResponse\x127\n" +
	"\bartifact\x18\x01 \x01(\v2\x1b.cloudscan.storage.ArtifactR\bartifact\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12c\n" +
	"\x0eupload_headers\x18\x03 \x03(\v2<.cloudscan.storage.CreateArtifactResponse.UploadHeadersEntryR\ruploadHeaders\x1a@\n" +
	"\x12UploadHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x12GetArtifactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10expires_in_hours\x18\x02 \x01(\x05R\x0eexpiresInHours\"q\n" +
	"\x13GetArtifactResponse\x127\n" +
	"\bartifact\x18\x01 \x01(\v2\x1b.cloudscan.storage.ArtifactR\bartifact\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\"'\n" +
	"\x15DeleteArtifactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x14ListArtifactsRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.cloudscan.storage.ArtifactTypeR\x04type\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x9b\x01\n" +
	"\x15ListArtifactsResponse\x129\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1b.cloudscan.storage.ArtifactR\tartifacts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\";\n" +
	"\x18InitiateMultipartRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"8\n" +
	"\x19InitiateMultipartResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"\x92\x01\n" +
	"\x18GetMultipartPartsRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\x1b\n" +
	"\tfrom_part\x18\x03 \x01(\x05R\bfromPart\x12\x1b\n" +
	"\tnum_parts\x18\x04 \x01(\x05R\bnumParts\"P\n" +
	"\x19GetMultipartPartsResponse\x123\n" +
	"\x05parts\x18\x01 \x03(\v2\x1d.cloudscan.storage.UploadPartR\x05parts\"_\n" +
	"\n" +
	"UploadPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"expiration\x18\x03 \x01(\tR\n" +
	"expiration\"\x90\x01\n" +
	"\x18CompleteMultipartRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x126\n" +
	"\x05parts\x18\x03 \x03(\v2 .cloudscan.storage.CompletedPartR\x05parts\"D\n" +
	"\rCompletedPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"M\n" +
	"\x19CompleteMultipartResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"expiration\x18\x02 \x01(\tR\n" +
	"expiration\"U\n" +
	"\x15AbortMultipartRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId*e\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSOURCE_CODE\x10\x01\x12\x10\n" +
	"\fSCAN_RESULTS\x10\x02\x12\n" +
	"\n" +
	"\x06REPORT\x10\x03\x12\a\n" +
	"\x03LOG\x10\x042\xc9\x06\n" +
	"\x0eStorageService\x12e\n" +
	"\x0eCreateArtifact\x12(.cloudscan.storage.CreateArtifactRequest\x1a).cloudscan.storage.CreateArtifactResponse\x12\\\n" +
	"\vGetArtifact\x12%.cloudscan.storage.GetArtifactRequest\x1a&.cloudscan.storage.GetArtifactResponse\x12R\n" +
	"\x0eDeleteArtifact\x12(.cloudscan.storage.DeleteArtifactRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\rListArtifacts\x12'.cloudscan.storage.ListArtifactsRequest\x1a(.cloudscan.storage.ListArtifactsResponse\x12t\n" +
	"\x17InitiateMultipartUpload\x12+.cloudscan.storage.InitiateMultipartRequest\x1a,.cloudscan.storage.InitiateMultipartResponse\x12t\n" +
	"\x17GetMultipartUploadParts\x12+.cloudscan.storage.GetMultipartPartsRequest\x1a,.cloudscan.storage.GetMultipartPartsResponse\x12t\n" +
	"\x17CompleteMultipartUpload\x12+.cloudscan.storage.CompleteMultipartRequest\x1a,.cloudscan.storage.CompleteMultipartResponse\x12X\n" +
	"\x14AbortMultipartUpload\x12(.cloudscan.storage.AbortMultipartRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/cloud-scan/cloudscan-storage/generated/protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_storage_proto_goTypes = []any{
	(ArtifactType)(0),                 // 0: cloudscan.storage.ArtifactType
	(*Artifact)(nil),                  // 1: cloudscan.storage.Artifact
	(*CreateArtifactRequest)(nil),     // 2: cloudscan.storage.CreateArtifactRequest
	(*CreateArtifactResponse)(nil),    // 3: cloudscan.storage.CreateArtifactResponse
	(*GetArtifactRequest)(nil),        // 4: cloudscan.storage.GetArtifactRequest
	(*GetArtifactResponse)(nil),       // 5: cloudscan.storage.GetArtifactResponse
	(*DeleteArtifactRequest)(nil),     // 6: cloudscan.storage.DeleteArtifactRequest
	(*ListArtifactsRequest)(nil),      // 7: cloudscan.storage.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),     // 8: cloudscan.storage.ListArtifactsResponse
	(*InitiateMultipartRequest)(nil),  // 9: cloudscan.storage.InitiateMultipartRequest
	(*InitiateMultipartResponse)(nil), // 10: cloudscan.storage.InitiateMultipartResponse
	(*GetMultipartPartsRequest)(nil),  // 11: cloudscan.storage.GetMultipartPartsRequest
	(*GetMultipartPartsResponse)(nil), // 12: cloudscan.storage.GetMultipartPartsResponse
	(*UploadPart)(nil),                // 13: cloudscan.storage.UploadPart
	(*CompleteMultipartRequest)(nil),  // 14: cloudscan.storage.CompleteMultipartRequest
	(*CompletedPart)(nil),             // 15: cloudscan.storage.CompletedPart
	(*CompleteMultipartResponse)(nil), // 16: cloudscan.storage.CompleteMultipartResponse
	(*AbortMultipartRequest)(nil),     // 17: cloudscan.storage.AbortMultipartRequest
	nil,                               // 18: cloudscan.storage.CreateArtifactResponse.UploadHeadersEntry
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 20: google.protobuf.Empty
}
var file_storage_proto_depIdxs = []int32{
	0,  // 0: cloudscan.storage.Artifact.type:type_name -> cloudscan.storage.ArtifactType
	19, // 1: cloudscan.storage.Artifact.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: cloudscan.storage.Artifact.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: cloudscan.storage.CreateArtifactRequest.type:type_name -> cloudscan.storage.ArtifactType
	1,  // 4: cloudscan.storage.CreateArtifactResponse.artifact:type_name -> cloudscan.storage.Artifact
	18, // 5: cloudscan.storage.CreateArtifactResponse.upload_headers:type_name -> cloudscan.storage.CreateArtifactResponse.UploadHeadersEntry
	1,  // 6: cloudscan.storage.GetArtifactResponse.artifact:type_name -> cloudscan.storage.Artifact
	0,  // 7: cloudscan.storage.ListArtifactsRequest.type:type_name -> cloudscan.storage.ArtifactType
	1,  // 8: cloudscan.storage.ListArtifactsResponse.artifacts:type_name -> cloudscan.storage.Artifact
	13, // 9: cloudscan.storage.GetMultipartPartsResponse.parts:type_name -> cloudscan.storage.UploadPart
	15, // 10: cloudscan.storage.CompleteMultipartRequest.parts:type_name -> cloudscan.storage.CompletedPart
	2,  // 11: cloudscan.storage.StorageService.CreateArtifact:input_type -> cloudscan.storage.CreateArtifactRequest
	4,  // 12: cloudscan.storage.StorageService.GetArtifact:input_type -> cloudscan.storage.GetArtifactRequest
	6,  // 13: cloudscan.storage.StorageService.DeleteArtifact:input_type -> cloudscan.storage.DeleteArtifactRequest
	7,  // 14: cloudscan.storage.StorageService.ListArtifacts:input_type -> cloudscan.storage.ListArtifactsRequest
	9,  // 15: cloudscan.storage.StorageService.InitiateMultipartUpload:input_type -> cloudscan.storage.InitiateMultipartRequest
	11, // 16: cloudscan.storage.StorageService.GetMultipartUploadParts:input_type -> cloudscan.storage.GetMultipartPartsRequest
	14, // 17: cloudscan.storage.StorageService.CompleteMultipartUpload:input_type -> cloudscan.storage.CompleteMultipartRequest
	17, // 18: cloudscan.storage.StorageService.AbortMultipartUpload:input_type -> cloudscan.storage.AbortMultipartRequest
	3,  // 19: cloudscan.storage.StorageService.CreateArtifact:output_type -> cloudscan.storage.CreateArtifactResponse
	5,  // 20: cloudscan.storage.StorageService.GetArtifact:output_type -> cloudscan.storage.GetArtifactResponse
	20, // 21: cloudscan.storage.StorageService.DeleteArtifact:output_type -> google.protobuf.Empty
	8,  // 22: cloudscan.storage.StorageService.ListArtifacts:output_type -> cloudscan.storage.ListArtifactsResponse
	10, // 23: cloudscan.storage.StorageService.InitiateMultipartUpload:output_type -> cloudscan.storage.InitiateMultipartResponse
	12, // 24: cloudscan.storage.StorageService.GetMultipartUploadParts:output_type -> cloudscan.storage.GetMultipartPartsResponse
	16, // 25: cloudscan.storage.StorageService.CompleteMultipartUpload:output_type -> cloudscan.storage.CompleteMultipartResponse
	20, // 26: cloudscan.storage.StorageService.AbortMultipartUpload:output_type -> google.protobuf.Empty
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
